Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-24.04"
    config.vm.define "tgellonS" do |server|
        server.vm.hostname = "tgellonS"
        server.vm.provider "virtualbox" do |vb|
            vb.memory = "2048"
            vb.cpus = "2"
            vb.customize ["modifyvm", :id, "--name", "tgellonS"]
        end
        server.vm.network "private_network", ip: "192.168.56.110"
        config.vm.synced_folder "./confs", "/vagrant/confs"
        server.vm.provision "shell", path: "scripts/k3s_server_setup.sh"
    end
end