Vagrant.configure("2") do |config|
    config.vm.box = "bento/debian-13.1"
    config.vm.define "tgellonS" do |server|
        server.vm.hostname = "tgellonS"
        server.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
            vb.cpus = "1"
        end
        server.vm.network "private_network", ip: "192.168.56.110"
        server.vm.provision "shell", path: "scripts/k3s_server_setup.sh"
    end
    config.vm.define "tgellonSW" do |server_worker|
        server_worker.vm.hostname = "tgellonSW"
        server_worker.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
            vb.cpus = "1"
        end
        server_worker.vm.network "private_network", ip: "192.168.56.111"
        server_worker.vm.provision "shell", path: "scripts/k3s_worker_setup.sh"
    end
end